#!/usr/bin/env cwl-runner

class: CommandLineTool

id: "YAP_MCSv3_clipOverlapCorrection"
label: "YAP MCSv3 clipOverlapCorrection"

cwlVersion: "v1.0"

doc: |
    Corrects the bam format generated by bamUtils clipOverlapping to be compatible with Bis-SNP.

dct:creator:
  "@id": "https://orcid.org/0000-0001-6231-4417"
  foaf:name: Karl Nordström
  foaf:mbox: "mailto:karl.nordstroem@uni-saarland.de"


requirements:
  - class: DockerRequirement
    dockerPull: "quay.io/biocontainers/YAP_MCSv3:0.0.1"

hints:
  - class: ResourceRequirement
    coresMin: 1
    ramMin: 4092
    outdirMin: 512000

baseCommand: ["clipOverlapCorrection"]

stdin: $( inputs.input )
stdout: $( inputs.output_name )

outputs:
  correctedSam:
    type: stdout

inputs:

  input:
    type: File
    doc: |
      The file to be adjusted.

  output_name:
    type: string
    doc: |
      Name of output file

