#!/usr/bin/env bash

name=getChrNames

printHelp(){
  echo -e "$name -i <bamFile>" >&2
}

while getopts ":i:h" opt; do
  case "$opt" in
    i) inputFile="$OPTARG" ;;
    h) printHelp; exit 0 ;;
    *) printHelp; exit 1 ;;
  esac
done

if [[ -z "$inputFile" ]]; then
  echo -e "ERROR ($name) $(date): All mandatory arguments must be set" >&2
  printHelp
  exit 1
fi

samtools view -H $inputFile |awk '/@SQ/ {print substr(,4)}'
