#!/usr/bin/env bash

name="multiQCwrapper"

printHelp(){
  echo -e "" >&2
  echo -e "combines all compatible log files to multiQC report" >&2
  echo -e "" >&2
  echo -e "Usage: $name <options>" >&2
  echo -e "" >&2
  echo -e " Mandatory options:" >&2
  echo -e "  -i FILE\tinputlog file (can be given multiple times)" >&2
  echo -e "  -o STR\toutput prefix" >&2
  echo -e "" >&2
}


while getopts "i:o:h" opt; do
  case "$opt" in
    i) inputFiles=("${inputFiles[@]}" "$OPTARG") ;;
    o) outputPrefix="$OPTARG" ;;
    h) printHelp; exit 0 ;;
    *) printHelp; exit 1 ;;
  esac
done

if [[ -z "$inputFiles" ]] || [[ -z "$outputPrefix" ]]; then
  echo -e "ERROR $(date) ($name): All mandatory options must be set" >&2
  printHelp
  exit 1
fi

mkdir -p ${outputPrefix}_logfiles

for file in ${inputFiles[@]}; do
  cp $file ${outputPrefix}_logfiles
done

multiqc -d ${outputPrefix}_logfiles -n ${outputPrefix} -ip

