#!/usr/bin/env cwl-runner

class: CommandLineTool

id: "YAP_MCSv3_clipOverlapCorrection"
label: "YAP MCSv3 clipOverlapCorrection"

cwlVersion: "v1.0"

doc: |
    Corrects the bam format generated by bamUtils clipOverlapping to be compatible with Bis-SNP.

dct:creator:
  "@id": "https://orcid.org/0000-0001-6231-4417"
  foaf:name: Karl Nordström
  foaf:mbox: "mailto:karl.nordstroem@uni-saarland.de"


requirements:
  - class: InlineJavascriptRequirement
  - class: InitialWorkDirRequirement
    listing:
      - $( inputs.scriptFolder )

hints:
  - class: ResourceRequirement
    coresMin: 1
    ramMin: 4092
    outdirMin: 512000
  - class: DockerRequirement
    dockerPull: "quay.io/biocontainers/bis-snp-utils:0.0.1--pl5.22.0_0"

baseCommand: ["bash", "scripts/clipOverlapCorrection"]

stdin: $( inputs.input )
stdout: $( inputs.output_name )

outputs:
  correctedSam:
    type: stdout

inputs:

  input:
    type: File
    doc: |
      The file to be adjusted.

  output_name:
    type: string
    doc: |
      Name of output file

  scriptFolder:
    type: Directory
    doc: |
      folder containing associated scripts

